### ISSUE TITLE
CaN i jOin?

### ISSUE THREAD

**Issue by ImNotEcy** [HorizonLN/MoonMC#1]
How can I join you?

**Comment by NullYu** [comment]
8支持eps user进来刺探情报

**Comment by ImNotEcy** [comment]
> 8支持eps user进来刺探情报
what is eps user?

**Comment by NullYu** [comment]
> > 8支持eps user进来刺探情报
> > what is eps user?

Epsilon User
另外2.5被开裂了

**Comment by ImNotEcy** [comment]
idc,I havent epsilon

**Comment by NullYu** [comment]
> idc,I havent epsilon

问个问题吧，相当基础
Override注解是否可以应用到由反射获取的类上

**Comment by trdyun** [comment]
whats your qq number

**Comment by ImNotEcy** [comment]
> 你的qq号码是多少
that's a joke,dont care pls

**Comment by ImNotEcy** [comment]
> > 你的qq号码是多少 
> > 这是个玩笑，请不要在意
I just posted an issue for fun，im sorry for that
